export const TEMPLATES = {
    generationSuccess: (prompt: string) =>
        `Create an informal response to a video of ${prompt} being generated by the agent. add "$apple" at the end. make it short. dont use hashtags.`,
};
